{
	"targets": [
		{
			"name": "Calculator",
			"debug": true,

			"sources": [
				"./*.cpp"
			],

			"includes": [
				"../KlemmUI/Include"
			],

			"libs": [
				"../KlemmUI/lib/Debug/KlemmUI-Debug",
				"../KlemmUI/lib/Debug/glew",
				"SDL2",
				"GL"
			]
		}
	]
}